### ISSUE TITLE
Can get Swup to work!!

### ISSUE THREAD

**Issue by shanewmurphy** [gmrchk/swupjs#1]
Its a shame you didn't include a barebones example.

I'm trying to see swup is working by using the example of: 

`out: function (next) {
    setTimeout(next, 2000)
}
`

My code is:
`let options = {
    animations: {
        '*': {
            out: function (next) {
                setTimeout(next, 9000)
            },
            in: function (next) {
                next()
            }
        }
    }
}
const swupjs = new Swupjs(options)
`

The result is no waiting 9 sec just loads the second page right away.

Also, I'd like to use anime.js to create the page transitions but honestly don't know how I'd do that. 
I've read the documentation a few times now but none the wiser.

**Comment by gmrchk** [comment]
I just pulled in a fresh version of swupjs from npm and standalone file from github and both are working as expected with your code (waits 9 seconds and replaces the content). There must be some other issue. Try enabling debugMode in options to see what is happening on your page in the console. 
```javascript
let options = {
    debugMode: true
}
```

I have never used anime.js, but I would guess you would go for something like this:
```javascript
animations: {
    '*': {
        out: function (next) {
            anime({
                targets: '#wrapper',
                opacity: 0,
                complete: next
            });
        },
        in: function (next) {
             anime({
                targets: '#wrapper',
                opacity: 1,
                complete: next
            });
        }
    }
}
```
Where `#wrapper` is some kind of element you want to fade out and fade in.

**Comment by shanewmurphy** [comment]
Hi, @gmrchk thanks for replying back to me!

Sadly I don't have much experience with JS :( but that said I should be able to implement the example explained of setTimeout(next, 2000) or the anime.js example has this plugin wishes to use JS for transitioning between pages. Either way, both examples aren't working for me.
I really hope to use this plugin with anime.js to create great transitions.

My Code 

![screen shot 2018-05-21 at 11 52 33](https://user-images.githubusercontent.com/3694619/40304563-20880ec2-5cef-11e8-8251-7a23c0c3c7d0.png)

Debug mode 

![screen shot 2018-05-21 at 11 52 47](https://user-images.githubusercontent.com/3694619/40304576-2ebd772a-5cef-11e8-9a30-cce932735a8a.png)

**Comment by gmrchk** [comment]
You have an error where your stack probably doesn't support ES6 syntax, and so your code with options most likely just doesn't compile. 

Replace "let" and "const" with "var" and you should be good to go.

**Comment by shanewmurphy** [comment]
Hi @gmrchk,
Yes, I saw you were using es6 syntax in example/documentation which I'd already changed "let" and "const" to var and still no enjoy. Even without the use anime.js and to use the setTimeout(next, 9000) doesn't work either.

**Comment by gmrchk** [comment]
I see. Can I see the code above line 10?

**Comment by shanewmurphy** [comment]
setTimeout example 

![screen shot 2018-05-21 at 18 17 35](https://user-images.githubusercontent.com/3694619/40320357-56023af8-5d23-11e8-8cff-e9ff4c04792e.png)

**Comment by shanewmurphy** [comment]
Anime.js example code:

![screen shot 2018-05-21 at 18 14 40](https://user-images.githubusercontent.com/3694619/40320382-6e2a3fae-5d23-11e8-89fe-2aa68a9839a6.png)

**Comment by shanewmurphy** [comment]
`var options = {
    debugMode: true,
    animations: {
        '*': {
            out: function (next) {
                setTimeout(next, 2000)
            },
            in: function (next) {
               next()
            }
        }
    }
}
var swupjs = new Swupjs(options)`

**Comment by shanewmurphy** [comment]
`
var options = {
    debugMode: true,
    animations: {
        '*': {
            out: function (next) {
                setTimeout(next, 2000)
            },
            in: function (next) {
               next()
            }
        }
    }
}
var swupjs = new Swupjs(options)
`

**Comment by gmrchk** [comment]
As you can see there is a bunch of errors and warnings showing up from JSLint and ESLint. None of those are issues of swupjs, except for the one that says 'Swupjs is not defined', which makes clear that swupjs is not loaded (as you're probably loading it using `script` tag, so the JSLint/ESLint don't know about it). I do not use ESLint, nor JSLint, so I can't help you with that...  but if I remember correctly, they are also used to compile your code, which means the compilation is prevented because of the errors.

You can try to disable both tools and try running your code as it is in your browser. I would also avoid `'use strict;'` for now. 

I'm closing the issue as I can't see any swupjs issue here. If you still have an issue when you solve all of those problems displayed above, feel free to reopen/create new issue.

**Comment by shanewmurphy** [comment]
swupjs.js is being loaded there's ref to it in the console when using Debug mode. Anyway thanks for taking the time to try & sort out and its a pity I couldn't get it to work on my end.
