### ISSUE TITLE
Possible to detect which link was clicked?

### ISSUE THREAD

**Issue by LukeCarlThompson** [gmrchk/swupjs#5]
Great library by the way. I've found it very powerful and reasonably straight forward to implement.

However, I'm integrating it into a wordPress site with a grid of images and getting stuck on an issue that seems more complicated than it needs to be.

I have a grid of images that link to posts. I'd like to animate elements between the pages starting with the element that was clicked. So I need to know which link was clicked so I can pass that as the target into an animation function.

As the event listener 'clickLink' is set to the document I can't use that. I've trying to write a workaround for some time now and running into more complexity than I expected.

So I thought I'd just check to see if I'm missing something and it's possible to just pass the clicked element into the animation function?

**Comment by gmrchk** [comment]
Hi @LukeCarlThompson and thanks,

Good idea! The way swup works with events could definitely use some revision and it's been some time on the list now. Including a "source element" is definitely a valuable information in some cases. I'm planning to look into this in the near future. If you have some other ideas you'd like to share, definitely don't hesitate to do so. 

In the meantime, I would probably create a click listener on the images you are mentioning and save the reference of a clicked element from the event into some global/accessible variable. You could even save it into your swup instance under some custom unused name, and get it from there in your animation function. Would that work for you?

**Comment by LukeCarlThompson** [comment]
Thanks for the reply and offer for a solution. That sounds like it would work. I was trying something similar but not getting very far, suspecting it might have had to do with the timing of both click events. Due to time constraints I've gone with an alternate solution for now. It's something I'll likely look into in the future though and try out again. Wish I had more time right now to figure it out.

**Comment by gmrchk** [comment]
Hi again @LukeCarlThompson!

I have modified how the [events work in swup](https://github.com/gmrchk/swup#events), and it should be much easier now to achieve what you are trying to do with the original events passed into handlers where possible. 

I will not add passing the source element into the animation function just yet, as there is a pretty reasonable workaround like the one mentioned above and it's really only needed in some specific cases. In case someone comes up with some more stuff that could be usefull in those function, I'm all up for just passing a bunch of info in there.

**Comment by LukeCarlThompson** [comment]
That's fantastic! Just a had quick look at the updated docs and the delegateTarget property is great. Looking forward to testing it out when I get a chance. Thanks a lot!

**Comment by mocodev** [comment]
I'm using video backgrounds throughout an app/kiosk we are building and trying to get specific scripts to run based on the target element that was clicked. Depending on the item clicked, videos are displayed and act as a transition between pages. Each page has a looping video as the background. Regardless of those details I'm having trouble understanding the above thread on how to have scripts fire using the `swup.on(clickLink)` event and using delegateTarget.

I currently have this working just to test out the basics:

```
function videoSwaps() {
   $('.video-02').addClass('visible-video');
   $('#video-player-02')[0].play();
   console.log("Video Replaced");  	
}

swup.on('clickLink', videoSwaps);
```

Now though I'm looking to have different video swaps happen depending on which link/button a user clicks.

Approaching it this way breaks the swup transition:

```
$('.btn-video-02').click(function(){
	$('.video-02').addClass('visible-video');
	$('#video-player-02')[0].play();
	console.log("Video Replaced");  
 	  }
 });
```
