### ISSUE TITLE
MAMP vs Real Hosting

### ISSUE THREAD

**Issue by esseifforte** [gmrchk/swupjs#9]
Hi!
on MAMP your animations works fine! (homepage > pages)
```javascript
animations: {
    'homepage*>': {
        // this is used for transition from homepage to any other page
    },
    '': {
        // this is used for any other transition, between the subpages OR from subpage to homepage
    },
}
```

but NOT online :((((
works only *> for all pages
this is the error
www.website.com/Cannot%20tween%20a%20null%20target.

UPDATE:
I understand what it depends on:
I basically put the site in a subfolder and not in the root root. Is there a way (especially when we have sites that reside in subfolders such as www.mysite.com/site), to solve the problem?

unfortunately I need to have a different animation for each page both incoming and outgoing. 
if I work only with default states (*>) is there a way, even using only the if else at least on the entry pages?

thank you for precious help

**Comment by gmrchk** [comment]
Hi, 

I would suggest defining the animation for multiple routes. This way you cover both options and still use only one animation definition. 

```javascript
var animationToHomepage = { ... }

animations: {
    'homepage>*': animationToHomepage,    // animation from homepage to any page on localhost
    'site>*': animationToHomepage,    // animation from homepage to any page online
    '*': {
        // whatever was here
    },
}
```

You can also manually select the animation by assigning the `data-swup-transition` to the link element, as is mentioned [here](https://github.com/gmrchk/swupjs#custom-animation-to-dynamic-pages).
